# -*- coding: utf-8 -*-
"""sqlite3.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pib1cJsy396UobFRIkY3ZU38bCFvBJcK
"""

import sqlite3
from sqlite3 import Error
def sql_connector(path):
  try:
    con=sqlite3.connect(path)
    cur=con.cursor()
    return con,cur
  except:
    print(Error)
    return None,None

def create_table(con,cur):
  cur.execute("CREATE TABLE  IF NOT EXISTS students(id INTEGER PRIMARY KEY,name TEXT ,age INTEGER,grade TEXT)")
  con.commit()

def insert_data(con,cur,entity):
  cur.executemany("INSERT INTO students VALUES(?,?,?,?)",entity)
  con.commit()

def fetch_data(con,cur):
  cur.execute("SELECT * FROM students")
  return cur.fetchall()


con,cur= sql_connector("students.db")
create_table(con,cur)
entity=[(3,'Alice',20,'A'),(4,'Bob',22,'B'),(5,'Claire',21,'C')]
insert_data(con,cur,entity )
data= fetch_data(con,cur)
for row in data:
  print(row)

con.close()